# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"sayHello": "00_core.ipynb",
         "dataset": "00_core.ipynb",
         "getFieldNames": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://philescandon.github.io/db/"

git_url = "https://github.com/philescandon/db/tree/master/"

def custom_doc_links(name): return None
